name: my_collection
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0+103000
# AABBCCX
# ABC2ケタずつ 1.0.0 => 100000
# 1.2.3 => 102030

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.0.0
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.4
  exif: ^3.1.1
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.3.7
  firebase_core: ^1.10.2
  firebase_storage: ^10.2.4
  fluttertoast: ^8.0.8
  flutter_hooks: ^0.18.0
  flutter_native_splash: ^2.0.5
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.2.3
  google_maps_flutter: ^2.1.1
  hooks_riverpod: ^1.0.0-dev.7
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+9
  introduction_screen: ^3.0.0
  json_serializable: ^6.1.1
  location: ^4.3.0
  page_transition: ^2.0.4
  package_info_plus: ^1.4.0
  riverpod: ^1.0.0-dev.7
  rounded_loading_button: ^2.0.9
  state_notifier: ^0.7.0
  url_launcher: ^6.0.20

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "72a663"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
  assets:
    - assets/images/
